### ISSUE TITLE
Have no clue how to install

### ISSUE THREAD

**Issue by craft2guardian** [jarvisdevlin/Reserve#1]
I have been trying for hours to install this but every time I get an error related to "_curses" and I have no clue why. Could you please make a tutorial on youtube showing how to do this

**Comment by jarvisdevlin** [comment]
I have updated the repo since I made a very stupid mistake, If you've installed python 3.8 or above and installed aiohttp via pip, you should be good to go once you redownloaded reserve.py from here.

Only thing I forgot is the fact that terminals are usually in different sizes and the ascii art being displayed is too big for curses to handle in your terminal and raised an Exception. I have fixed the issue by forcing the terminal to go a lot bigger so you shouldn't have any issues if you are running this on Windows, macOS or Linux.

If anything else pops up for you, ask here or I'm closing the issue.

**Comment by craft2guardian** [comment]
I had launched it in PowerShell since the file kept closing and it said this: Traceback (most recent call last):
  File "C:\users\PC\desktop\reserve.py", line 2, in <module>
    import os, hashlib, aiohttp, curses, threading
  File "C:\Users\PC\AppData\Local\Programs\Python\Python313\Lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'.

I also don't know how to change the geometry dash servers. I would have replied quicker but my school blocked GitHub and I couldn't.

**Comment by jarvisdevlin** [comment]
Try using `pip install windows-curses`, also open the exe up in Notepad++ and do a find and replace for `https://www.boomlings.com/database`

**Comment by jarvisdevlin** [comment]
closed
